# Generated by Django 2.2.5 on 2019-09-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3, verbose_name='Currency')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw')], verbose_name='Transaction Type')),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3, verbose_name='Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='atm.Transaction', verbose_name='Transaction detail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
